build:
    script:
    - 'cd MobileLab1'
    - 'nuget.exe restore'
    - '"/Library/Frameworks/Mono.framework/Versions/Current/msbuild.exe" MobileLab1.sln'
    artifacts:
        paths:
        - 'MobileLab1/MobileLab1/bin/Debug/netcoreapp3.1'